### ISSUE TITLE
[Request] Add Matt's Monster Pack from ModDB?

### ISSUE THREAD

**Issue by mattbratt11** [mridlen/Oblige_Realm667#160]
Hi. I'm Matt, the Maker of Matt's Monsters and Stuff GZDoom Mod from ModDB.
More info here if interested:
[https://www.moddb.com/games/doom-ii/addons/matts-monster-pack](url)
Would any of that stuff be added in the next release? Thank you!

**Comment by mridlen** [comment]
That's a lot of monsters! Fortunately, you have them in wad format, so this will make my job easier.

**Comment by mridlen** [comment]
Why did you make a Shade Elemental?????? That's like the worst enemy ever. :stuck_out_tongue_winking_eye: 

This one is going to be off by default. :smile:

**Comment by mattbratt11** [comment]
I've updated the Shade Soul and Elemental a while ago, so they won't spam as many clones as often.
That's the update so their clones die if you wait a while, but only while you destroy the Shade Elemental and its Souls.

**Comment by mridlen** [comment]
I guess I'll call it "Matt's Shade" to differentiate it from the other shade (still I admire your masochism). Thanks for the info and thanks for all the hard work on the monsters. These will go great in my mod.

I'm thinking I am going to create a jokewad menu and put the Plasma Beacon in it. I don't have any inventory type items yet.

Everything else is going live in the next update. Total of 421 monster resource wads.

**Comment by mattbratt11** [comment]
Thanks very much!

**Comment by mridlen** [comment]
This is live. Closing out the issue.
